app_mode: "dev"
app_name: "czthree"
db_type: "mysql"
dsn: "czthree:pass_to_czthree@tcp(127.0.0.1:3306)/czthree?parseTime=true"
jwt_signing_key: "xxxxxxxxx111111111111111222222222223333333333333"
jwt_expiration: 120
recaptcha_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
recaptcha_secret: "123test"
tls_key_path: "./data/certs/domain.key"
tls_cert_path: "./data/certs/chained.pem"
mail_smtphost: "smtp.gmail.com"
mail_smtpport: "587"
mail_username: "admin@gmail.com"
mail_password: "xxxxxxxxxxx"
app_fqdn: "czthree"
http_entrypoint: "czthree:3000"
webserv_name: "czthree-server"
google_client_id: "xxxxxxxxxxxxxxx"
google_credential_file: "./data/credential.json"
google_redirect_path: "/oauth/googleuser"
app_secret_key: "someSecretUtf8ForStrongValidJwtCryptography"
biz_name: "czthree.site"
biz_shortname: "czthree"
biz_email: "info@gmail.com"
biz_phone: "0000000000"
biz_phone2: "0000000000"
biz_logo: "favicon.ico"
